version: "3.8"

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongo          # nome del servizio Mongo nel compose
      MONGO_PORT: 27017
      MONGO_DB: your_db_name     # metti il nome del DB che vuoi usare
    volumes:
      - ./logs:/code/logs   # <-- qui monti la cartella logs dell'host nel container

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"


  frontend:
    build:
      context: ./app/Frontend/DatabaseGUI
      dockerfile: Dockerfile
    ports:
       - "5174:5173"


